# TODO: 'snapcraft register <name>'
name: protonmail-bridge
icon: snap/gui/protonmail-bridge.svg
summary: Proton Mail Bridge application
version: 3.14.0
description: |
  NOTE: This is a wrapper of the official package, but it is not verified,
  affiliated with, or supported by Proton AG.

  Proton Mail Bridge is a desktop application that runs in the background,
  encrypting and decrypting messages as they enter and leave your computer.

website: https://proton.me/mail/bridge
contact: https://github.com/pedro-avalos/protonmail-bridge-snap/issues
issues: https://github.com/pedro-avalos/protonmail-bridge-snap/issues
source-code: https://github.com/ProtonMail/proton-bridge

# XXX: On core22 for now only because of kde-neon-6
base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

# TODO: Add bridge and bridge-gui as apps?
apps:
  protonmail-bridge:
    command: usr/bin/protonmail-bridge
    desktop: usr/share/applications/protonmail-bridge.desktop
    # TODO: Test if the snap works with only gnome or only kde-neon-6?
    extensions:
      - gnome
      - kde-neon-6
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - gsettings
      - password-manager-service  # TODO: Check that it's connected
      - network
      - network-bind
      - system-observe  # TODO: Warnings in snappy-debug, required?
      - process-control  # TODO: Warnings in snappy-debug, required?

parts:
  protonmail-bridge:
    plugin: dump
    source-type: deb
    source: https://proton.me/download/bridge/protonmail-bridge_${SNAPCRAFT_PROJECT_VERSION}-1_amd64.deb
    override-build: |
      snapcraftctl build
      ln -sfn ../lib/protonmail/bridge/proton-bridge $SNAPCRAFT_PART_INSTALL/usr/bin/protonmail-bridge
