name: protonmail-bridge
icon: snap/gui/protonmail-bridge.svg
title: Proton Mail Bridge
summary: Proton Mail Bridge application
version: 3.14.0
license: GPL-3.0
description: |
  NOTE: This is a wrapper of the official package, but it is not verified,
  affiliated with, or supported by Proton AG.

  You need to have a keychain in order to run the Proton Mail Bridge. To allow
  access to the keychain, you have to manually connect the
  `password-manager-service` plug. See more information about this interface
  here: https://snapcraft.io/docs/password-manager-service-interface.

  `sudo snap connect protonmail-bridge:password-manager-service`

  Proton Mail Bridge is a desktop application that runs in the background,
  encrypting and decrypting messages as they enter and leave your computer.

website: https://proton.me/mail/bridge
contact: https://github.com/pedro-avalos/protonmail-bridge-snap/issues
issues: https://github.com/pedro-avalos/protonmail-bridge-snap/issues
source-code: https://github.com/ProtonMail/proton-bridge

base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

apps:
  protonmail-bridge:
    command: usr/bin/protonmail-bridge
    desktop: usr/share/applications/protonmail-bridge.desktop
    common-id: ch.protonmail.protonmail-bridge
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/protonmail/bridge/lib
    extensions:
      - gnome
      - kde-neon-6
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - gsettings
      - home
      - removable-media
      - password-manager-service
      - network
      - network-bind
      - hardware-observe
      - system-observe
      - process-control

  cli:
    command: usr/lib/protonmail/bridge/bridge
    environment:
      XDG_CACHE_HOME: $SNAP_USER_DATA/.cache
      XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
      XDG_DATA_HOME: $SNAP_USER_DATA/.local/share
    plugs:
      - home
      - removable-media
      - password-manager-service
      - network
      - network-bind
      - hardware-observe
      - system-observe
      - process-control

parts:
  protonmail-bridge:
    plugin: make
    source-type: git
    source: https://github.com/protonmail/proton-bridge.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    override-pull: |
      craftctl default
      git apply --ignore-space-change --ignore-whitespace $CRAFT_PROJECT_DIR/snap/local/patches/*.patch
    build-snaps:
      - go
      - cmake
    build-packages:
      - libicu-dev
      - unzip
      - zip
    stage-packages:
      - libmd4c0
      - libdouble-conversion3
      - libsecret-1-0
    build-environment:
      - PATH: $PATH:/snap/kf6-core22/current/usr/bin/qt6
      - QT_LIB_PATH: /snap/kf6-core22/current/usr/lib/x86_64-linux-gnu
      - QT_QML_PATH: /snap/kf6-core22/current/usr/lib/x86_64-linux-gnu/qt6/qml
      - QT_PLUGIN_PATH: /snap/kf6-core22/current/usr/lib/x86_64-linux-gnu/qt6/plugins
    override-build: |
      make build

      mkdir -p $CRAFT_PART_INSTALL/usr/share/doc/protonmail/bridge \
        $CRAFT_PART_INSTALL/usr/lib/protonmail/bridge \
        $CRAFT_PART_INSTALL/usr/share/applications \
        $CRAFT_PART_INSTALL/usr/bin

      cp $CRAFT_PART_BUILD/cmd/Desktop-Bridge/deploy/linux/Changelog.md \
        $CRAFT_PART_INSTALL/usr/share/doc/protonmail/bridge/
      cp $CRAFT_PART_BUILD/cmd/Desktop-Bridge/deploy/linux/LICENSE \
        $CRAFT_PART_INSTALL/usr/share/doc/protonmail/bridge/

      cp -r $CRAFT_PART_BUILD/cmd/Desktop-Bridge/deploy/linux/lib \
        $CRAFT_PART_INSTALL/usr/lib/protonmail/bridge/
      cp -r $CRAFT_PART_BUILD/cmd/Desktop-Bridge/deploy/linux/plugins \
        $CRAFT_PART_INSTALL/usr/lib/protonmail/bridge/
      cp -r $CRAFT_PART_BUILD/cmd/Desktop-Bridge/deploy/linux/qml \
        $CRAFT_PART_INSTALL/usr/lib/protonmail/bridge/

      cp $CRAFT_PART_BUILD/cmd/Desktop-Bridge/deploy/linux/proton-bridge \
        $CRAFT_PART_INSTALL/usr/lib/protonmail/bridge/
      cp $CRAFT_PART_BUILD/cmd/Desktop-Bridge/deploy/linux/bridge-gui \
        $CRAFT_PART_INSTALL/usr/lib/protonmail/bridge/
      cp $CRAFT_PART_BUILD/cmd/Desktop-Bridge/deploy/linux/bridge \
        $CRAFT_PART_INSTALL/usr/lib/protonmail/bridge/

      cp $CRAFT_PART_BUILD/cmd/Desktop-Bridge/deploy/linux/proton-bridge.desktop \
        $CRAFT_PART_INSTALL/usr/share/applications/protonmail-bridge.desktop

      ln -sfn ../lib/protonmail/bridge/proton-bridge \
        $CRAFT_PART_INSTALL/usr/bin/protonmail-bridge
